//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockId { get; set; }
        public string StockCode { get; set; }
        public string Status { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Dateofentry { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Products Products { get; set; }
        public virtual Store Store { get; set; }
    }
}
